#--------------------------
#Url del Menu Principal
#--------------------------
index:
  path: /
  controller: App\Controller\DefaultController::index

home:
  path: /home
  controller: App\Controller\DefaultController::home
 
estadisticas:
  path: /estadisticas
  controller: App\Controller\DefaultController::home

documentos:
  path: /documentos
  controller: App\Controller\DefaultController::home

archivos:
  path: /archivos
  controller: App\Controller\DefaultController::home

configuracion:
  path: /configuracion
  controller: App\Controller\DefaultController::home
