#--------------------------
#Url del Menu Principal
#--------------------------
index:
  path: /
  controller: App\Controller\DefaultController::index

home:
  path: /app/
  controller: App\Controller\DefaultController::home
 
estadisticas:
  path: /app/estadisticas
  controller: App\Controller\DefaultController::home

documentos:
  path: /app/documentos
  controller: App\Controller\DefaultController::home

archivos:
  path: /app/archivos
  controller: App\Controller\DefaultController::home

configuracion:
  path: /app/configuracion
  controller: App\Controller\DefaultController::home
